### Version information ##########
#
# Information included in the release that this branch documents.
# This information is used by the index.release-data.json file to generate a release-data.json file.
#
# version = The version this branch documents. `<MAJ>.<MIN>`
# release_date = The release date in ISO 8601 format: `YYYY-MM-DD`.
# github_branch = The repo branch for this version. For example, `release-<MAJ>.<MIN>`.
# deprecated = Whether this version is deprecated. `true` or `false`.
# eol = Whether this version is EOL. `true` or `false`.
##################################

[release_data]
version = ""
release_date = ""
deprecated = false
eol = false
github_branch = ""


breadcrumbs = true

[[breadcrumb_base]]
breadcrumb = "Docs"
url = "https://docs.chef.io"
